package com.crossoverJie.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * AcctUser generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "salesstore")
//@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6980093847795726310L;
	private int id;
	private String username;
	private String password;
	private Date registerTime;
	//private Set<AcctRole> acctRoles = new HashSet<AcctRole>(0);

	public User() {

	}

//	public AcctUser(String id, String nickName) {
//		this.id = id;
//		this.nickName = nickName;
//	}
//
//	public AcctUser(String id, String nickName, String telephone,
//			Date registerTime, Set<AcctRole> acctRoles) {
//		this.id = id;
//		this.nickName = nickName;
//		this.telephone = telephone;
//		this.registerTime = registerTime;
//		this.acctRoles = acctRoles;
//	}

	@Id
	@Column(name = "id", unique = true, nullable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_time", length = 19)
	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	
	@Column(name = "password")
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

//	@JsonIgnoreProperties(value={"acctUsers", "acctAuthorities"})
//	@ManyToMany(fetch = FetchType.LAZY)
//	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
//	@JoinTable(name = "acct_user_role", catalog = "work", joinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) })
//	public Set<AcctRole> getAcctRoles() {
//		return this.acctRoles;
//	}
//
//	public void setAcctRoles(Set<AcctRole> acctRoles) {
//		this.acctRoles = acctRoles;
//	}
}
